# Generated by Django 4.2.6 on 2023-10-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('type', models.CharField(choices=[('PC', 'Компьютер'), ('Notebook', 'Ноутбук'), ('Smart', 'Смартфон')], default='PC', max_length=50, verbose_name='Тип')),
                ('character', models.TextField(max_length=100, verbose_name='Характеристика')),
                ('price', models.IntegerField(max_length=50, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'список товаров',
            },
        ),
    ]
